### ISSUE TITLE
Remove shared automation manager modules

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ansible_tower#181]
While supporting an embedded automation manager and an ansible tower provider, most of the functionality was done in shared modules that were then included in those two classes.

Now that embedded ansible has moved to use ansible-runner not embedded tower we can remove all of this complexity.

**Comment by jameswnl** [comment]
Done in https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/186
