### ISSUE TITLE
RFE: Support configuring self-signed certificates

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-ansible_tower#40]
AFAICT this provider only supports turning verify_ssl off, and indeed some users are resorting to that:
http://talk.manageiq.org/t/how-to-create-ansible-tower-provider-via-api/2142 (though they have problems doing it via API)

This is suboptimal from security perspective; ideally if Tower has self-signed certificate, ManageIQ could be configured to trust the specific internal CA that generated it.
**It's probably doable now by editing the machine's CA bundle** — but that's not friendly (esp. on multi-appliance install).  Ideally there should be a way to configure a CA to trust per-provider, from the UI (and API).

(I've added similar support in openshift provider, and assisted for ovirt provider, happy to help if you want to work on this...)

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
