### ISSUE TITLE
Move VCR recording guide

### ISSUE THREAD

**Issue by Glutexo** [ManageIQ/manageiq-providers-ansible_tower#77]
A guide covering “Maintaining cassettes for new specs” is located in [/spec/support/ansible_shared/automation_manager/refresher.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/refresher.rb#L3). However, there are currently more specs that use VCR cassettes: namely [refresher_v2.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/refresher_v2.rb), [refresh_configuartion_script_source.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb), [refresh_configuartion_script_source_v2.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source_v2.rb) and [event_catcher/stream.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/event_catcher/stream.rb).

Because of that I’d like to see the guide somewhere else. Either there can be a document somewhere like /spec/support/vcr_guide.md, or it can be included the way it is now as a huge block comment in [/spec/support/vcr_helper.rb](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/vcr_helper.rb) instead. It the particular spec files, there can be only a short reference to the guide.

Do you agree with this change, @jameswnl?

**Comment by Glutexo** [comment]
@miq-bot add @jameswnl

**Comment by Glutexo** [comment]
@miq-bot assign @jameswnl

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue

**Comment by Glutexo** [comment]
I took a look and it is still relevant. Although the _refresher_v2.rb_ and _refresh_configuartion_script_source_v2.rb_ files are now gone, the remaining files are still there, dealing with VCR cassettes. The guide is still somewhat hidden in the [_refresher.rb_](
https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/ansible_shared/automation_manager/refresher.rb) file. I still think it would be good to move it either to the [_vcr_helper.rb_](
https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/spec/support/vcr_helper.rb) file or create a Markdown document for that.

Humbly reopening. Maybe @jameswnl would be willing to spare a minute? Or I can do it at some point when I’d feel like switching to something different for a while.
@miq-bot open_issue

**Comment by JPrause** [comment]
Thanks @Glutexo 
@bdunne can you reopen this issue.
@miq-bot remove_label stale
