### ISSUE TITLE
Support custom credentials type for Embedded Ansible

### ISSUE THREAD

**Issue by miha-plesko** [ManageIQ/manageiq-providers-ansible_tower#96]
We would like to use Embedded Ansible for one of the providers ([Nuage](https://github.com/manageiq/manageiq-providers-nuage)) and would like to make use of **Automation -> Ansible -> Credentials** feature so that user doesn't always need to input credentials.

Embedded Ansible is implemented through AWX meaning that AWX needs to be aware of Nuage credentials type, which it isn't the case. Now, AWX offers a simple way to dynamically register custom credentials type, but it has to be done via API v2, which isn't yet supported by ManageIQ.

Q1: Is integrating Nuage credential type into AWX setting really the only way to go?
Q2: What if AWX maintainer refuses to accept the PR?
Q3: Is there no "local" way where miq would store the credentials locally and forcibly use them when running playbooks? I mean, it feels odd that we need to modify AWX upstream even if we only want to use Embedded Ansible.

/cc @jameswnl @carbonin @himdel I kindly ask for a suggestion on how to proceed.

**Comment by jameswnl** [comment]
> Q1: Is integrating Nuage credential type into AWX setting really the only way to go?
> Q2: What if AWX maintainer refuses to accept the PR?

@miha-plesko there's no need to create PR to AWX. See their `custom credential types` at [here](http://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html).

So the question is MIQ's support on the v.2 API and its custom credential type. You can raise a RFE in https://bugzilla.redhat.com.

**Comment by miha-plesko** [comment]
@jameswnl thanks for reply. So I've been playing with custom credential types today and as far as I can tell we don't even really need to upgrade entire Embedded Ansible codebase to v2 API, we could do it "partially" i.e. just enough to support inventoring/creating credentials leaving other parts intact.

In other words, we could just make sure that [this specific API call](https://github.com/ManageIQ/manageiq-providers-ansible_tower/blob/master/app/models/manageiq/providers/ansible_tower/shared/automation_manager/credential.rb#L9) gets invoked using `/api/v2` endpoint so that we can both *list* and *create* credential_types and also create credentials using custom types (disabled in `v1`)

I'm working on this right now and would be happy to hear your opinion.

**Comment by jameswnl** [comment]
@miha-plesko see the quoted text from the API doc page:
> Custom credentials will not be managed by the V1 API; if a user defines a custom credential type, its credentials will not show up in the V1 API
POSTs to V1 credential API will transparently work with migrated CredentialTypes/Credentials

V1 API doesn't work for that. However, I am not entirely sure about "POSTs to V1 ...".  If you can play with the V1 API and find out what it mean, that'd be great.
